version: "3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - nifinetw
  nifi1:
    image: apache/nifi:latest
    ports:
      - 6980:8080
    networks:
      - nifinetw      
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min  
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_state:/data/nifi/nifi-current/state
      - nifi_db:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository       
  nifi2:
    image: apache/nifi:latest
    ports:
      - 6979:8080
    networks:
      - nifinetw      
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
      - nifi_conf1:/opt/nifi/nifi-current/conf
      - nifi_state1:/data/nifi/nifi-current/state
      - nifi_db1:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile1:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content1:/opt/nifi/nifi-current/content_repository
      - nifi_provenance1:/opt/nifi/nifi-current/provenance_repository 
  nifi3:
    image: apache/nifi:latest
    ports:
      - 6978:8080
    networks:
      - nifinetw      
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
      - nifi_conf2:/opt/nifi/nifi-current/conf
      - nifi_state2:/data/nifi/nifi-current/state
      - nifi_db2:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile2:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content2:/opt/nifi/nifi-current/content_repository
      - nifi_provenance2:/opt/nifi/nifi-current/provenance_repository       
networks:
  nifinetw:
    driver: bridge
volumes:
  nifi_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_conf'
  nifi_state:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_state'    
  nifi_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_db'  
  nifi_flowfile:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_flowfile' 
  nifi_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_content'
  nifi_provenance:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_provenance'
  nifi_conf1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_conf1'
  nifi_state1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_state1'    
  nifi_db1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_db1'  
  nifi_flowfile1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_flowfile1' 
  nifi_content1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_content1'
  nifi_provenance1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_provenance1'
  nifi_conf2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_conf2'
  nifi_state2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_state2'    
  nifi_db2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_db2'  
  nifi_flowfile2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_flowfile2' 
  nifi_content2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_content2'
  nifi_provenance2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: 'C:/Users/PC/Desktop/nifi/cluster/nifi_provenance2'    